# Generated by Django 3.1.5 on 2021-02-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publish',
        ),
    ]
